// @deprecated IPC channel 定义已下放到各 block 的 shared/xxx.channels.js
// 新代码应从对应 block 的 channels 文件导入
// 此文件保留用于向后兼容，将在后续版本移除
const IPC = Object.freeze({
  PTY_CREATE: "pty:create",
  PTY_INPUT: "pty:input",
  PTY_RESIZE: "pty:resize",
  PTY_DESTROY: "pty:destroy",
  PTY_SNAPSHOT: "pty:snapshot",
  PTY_DATA: "pty:data",
  PTY_EXIT: "pty:exit",
  PROJECT_LIST: "project:list",
  PROJECT_ADD: "project:add",
  PROJECT_REMOVE: "project:remove",
  SESSION_LIST: "session:list",
  SESSION_CREATE: "session:create",
  SESSION_START: "session:start",
  SESSION_RENAME: "session:rename",
  SESSION_SUGGEST_TITLE: "session:suggest:title",
  SESSION_SYNC_PROJECT: "session:sync:project",
  SESSION_REORDER: "session:reorder",
  SESSION_STATS: "session:stats",
  SESSION_ARCHIVE: "session:archive",
  SESSION_ARCHIVE_LIST: "session:archive:list",
  SESSION_RESTORE: "session:restore",
  FILE_TREE_READ: "file:tree:read",
  FILE_OPEN_PATH: "file:open:path",
  FILE_ATTACHMENT_SAVE: "file:attachment:save",
  FILE_ATTACHMENT_SAVE_BUFFER: "file:attachment:save:buffer",
  SKILLGEN_RUN: "skillgen:run",
  WINDOW_SET_TRAFFIC_LIGHT: "window:traffic-light:set",
  WINDOW_OPEN_EXTERNAL: "window:open-external",
  WINDOW_MINIMIZE: "window:minimize",
  WINDOW_TOGGLE_MAXIMIZE: "window:toggle-maximize",
  WINDOW_CLOSE: "window:close",
  APP_LOG: "app:log",
  SETTINGS_CLAUDE_GET: "settings:claude:get",
  SETTINGS_CLAUDE_SAVE: "settings:claude:save",
  SETTINGS_PROVIDER_TEST: "settings:provider:test",
  SETTINGS_PROVIDER_OAUTH_LOGIN: "settings:provider:oauth:login",
  SETTINGS_PROVIDER_OAUTH_PROBE: "settings:provider:oauth:probe",
  SETTINGS_PROVIDER_OAUTH_LINKS: "settings:provider:oauth:links",
  SETTINGS_PROVIDER_PROXY_TEST: "settings:provider:proxy:test",
  SETTINGS_RUNTIME_CLEAN: "settings:runtime:clean"
});

module.exports = { IPC };
