import { useEffect, useRef } from "react";
import { Terminal } from "@xterm/xterm";
import { FitAddon } from "@xterm/addon-fit";
import { WebLinksAddon } from "@xterm/addon-web-links";
import { ptyBridge } from "../../../bridge/pty.bridge";
import { logBridge } from "../../../bridge/log.bridge";
import { fileBridge } from "../../../bridge/file.bridge";
import { useSessionStore } from "../../../store/session.store";

type TermEntry = {
  term: Terminal;
  fitAddon: FitAddon;
};

const MIN_SAFE_WIDTH = 320;
const MIN_SAFE_HEIGHT = 120;

function stripTerminalReports(data: string) {
  return data
    // Cursor position / device attribute / status reports generated by xterm.
    .replace(/\x1b\[\??[0-9;]*[Rcn]/g, "")
    // OSC color query replies, for example ESC ] 10;rgb:cccc/cccc/cccc BEL.
    .replace(/\x1b\](?:10|11|12|4;[0-9]+);rgb:[0-9a-fA-F/]+\x07/g, "")
    .replace(/\x1b\](?:10|11|12|4;[0-9]+);rgb:[0-9a-fA-F/]+\x1b\\/g, "");
}

function stripEchoedTerminalReports(data: string) {
  return data
    .split(/\r?\n/)
    .filter((line) => {
      const trimmed = line.trim();
      if (/^(?:;)?(?:\d+R|\d+c\d+)(?:;|$)/.test(trimmed)) return false;
      if (/^zsh: (?:command not found|no such file or directory): (?:\d+R|\d+c\d+|rgb:)/.test(trimmed)) return false;
      return true;
    })
    .join("\r\n");
}

function getSessionProvider(sessionId: string) {
  const session = useSessionStore.getState().sessions.find((item) => item.sessionId === sessionId);
  return String(session?.provider || "").toLowerCase();
}

function hasBlockedCodexTerminalMode(params: (number | number[])[]) {
  const blockedModes = new Set([47, 1047, 1048, 1049]);
  for (const param of params || []) {
    if (Array.isArray(param)) {
      if (param.some((value) => blockedModes.has(Number(value)))) return true;
      continue;
    }
    if (blockedModes.has(Number(param))) return true;
  }
  return false;
}

function installCodexScrollbackGuard(sessionId: string, term: Terminal) {
  if (getSessionProvider(sessionId) !== "codex") return;
  const intercept = (params: (number | number[])[]) => hasBlockedCodexTerminalMode(params);
  try {
    term.parser.registerCsiHandler({ prefix: "?", final: "h" }, intercept);
    term.parser.registerCsiHandler({ prefix: "?", final: "l" }, intercept);
  } catch (error) {
    logBridge.write({
      level: "warn",
      scope: "terminal",
      message: "Failed to install Codex scrollback guard",
      meta: { sessionId, error: error instanceof Error ? error.message : String(error) }
    });
  }
}

async function handleClipboardPasteAsync(sessionId: string, cwd: string, term: Terminal) {
  logBridge.write({ level: "info", scope: "terminal", message: "[paste] async handler started", meta: { sessionId } });

  try {
    if (navigator.clipboard && typeof navigator.clipboard.read === "function") {
      const clipboardItems = await navigator.clipboard.read();
      logBridge.write({ level: "info", scope: "terminal", message: "[paste] clipboard.read() success", meta: { sessionId, count: clipboardItems.length, types: clipboardItems.flatMap((i) => i.types) } });

      for (const item of clipboardItems) {
        const imageType = item.types.find((t) => t.toLowerCase().startsWith("image/"));
        if (imageType) {
          logBridge.write({ level: "info", scope: "terminal", message: "[paste] image found via read()", meta: { sessionId, mimeType: imageType } });
          const blob = await item.getType(imageType);
          const arrayBuffer = await blob.arrayBuffer();
          const bytes = new Uint8Array(arrayBuffer);
          let binary = "";
          const chunk = 8192;
          for (let i = 0; i < bytes.length; i += chunk) {
            binary += String.fromCharCode(...bytes.subarray(i, i + chunk));
          }
          const base64 = btoa(binary);

          const result = await fileBridge.saveAttachmentImageBuffer({
            cwd,
            sessionId,
            base64,
            mimeType: imageType
          });

          if (result?.ok && result.relPath) {
            logBridge.write({ level: "info", scope: "terminal", message: "[paste] image saved", meta: { sessionId, relPath: result.relPath } });
            ptyBridge.input(sessionId, `@${result.relPath}`);
            return;
          }
        }
      }
    }

    // 没有图片或 read() 不可用，回退到文本粘贴
    const text = await navigator.clipboard.readText();
    if (text) {
      logBridge.write({ level: "info", scope: "terminal", message: "[paste] falling back to text paste", meta: { sessionId, textLength: text.length } });
      term.paste(text);
    } else {
      logBridge.write({ level: "info", scope: "terminal", message: "[paste] clipboard empty", meta: { sessionId } });
    }
  } catch (error) {
    logBridge.write({ level: "warn", scope: "terminal", message: "[paste] async handler error", meta: { sessionId, error: error instanceof Error ? error.message : String(error) } });
    // 最后尝试文本粘贴
    try {
      const text = await navigator.clipboard.readText();
      if (text) term.paste(text);
    } catch {
      // 完全失败
    }
  }
}

export function usePty() {
  const terminalRef = useRef<Map<string, TermEntry>>(new Map());
  const containerRef = useRef<Map<string, HTMLDivElement>>(new Map());
  const resizeObserverRef = useRef<Map<string, ResizeObserver>>(new Map());
  const fitRafRef = useRef<Map<string, number>>(new Map());
  const bufferRef = useRef<Map<string, string>>(new Map());
  const lastResizeRef = useRef<Map<string, { cols: number; rows: number }>>(new Map());
  const replayMutedRef = useRef<Set<string>>(new Set());
  const pasteCleanupRef = useRef<Map<string, () => void>>(new Map());
  const pasteInFlightRef = useRef<Set<string>>(new Set());
  const activeSessionIdRef = useRef<string | null>(null);

  const activeSessionId = useSessionStore((state) => state.activeSessionId);
  const ingestOutput = useSessionStore((state) => state.ingestOutput);
  const markExited = useSessionStore((state) => state.markExited);
  const refreshRuntimeStatuses = useSessionStore((state) => state.refreshRuntimeStatuses);

  activeSessionIdRef.current = activeSessionId;

  function appendBuffer(sessionId: string, chunk: string) {
    const prev = bufferRef.current.get(sessionId) || "";
    const merged = prev + chunk;
    const limit = 300000;
    bufferRef.current.set(sessionId, merged.length > limit ? merged.slice(-limit) : merged);
  }

  function getPaneRect(sessionId: string) {
    const container = containerRef.current.get(sessionId);
    if (!container) return null;
    return container.getBoundingClientRect();
  }

  function safeResizePty(sessionId: string, entry: TermEntry) {
    if (activeSessionIdRef.current !== sessionId) {
      return;
    }
    const rect = getPaneRect(sessionId);
    if (!rect) return;
    if (rect.width < MIN_SAFE_WIDTH || rect.height < MIN_SAFE_HEIGHT) {
      logBridge.write({
        level: "warn",
        scope: "terminal",
        message: "Skip PTY resize: pane too small",
        meta: {
          sessionId,
          width: Math.floor(rect.width),
          height: Math.floor(rect.height)
        }
      });
      return;
    }

    const cols = Math.max(1, entry.term.cols || 120);
    const rows = Math.max(1, entry.term.rows || 36);
    ptyBridge.resize(sessionId, cols, rows);
    lastResizeRef.current.set(sessionId, { cols, rows });
  }

  function scrollToBottomIfActive(sessionId: string, term: Terminal) {
    if (activeSessionIdRef.current !== sessionId) return;
    try {
      term.scrollToBottom();
    } catch {
    }
  }

  function isAtScrollBottom(term: Terminal) {
    try {
      const buffer = term.buffer.active;
      return buffer.baseY - buffer.viewportY <= 1;
    } catch {
      return true;
    }
  }

  function writeLiveTerminalData(sessionId: string, term: Terminal, data: string) {
    const shouldFollowOutput = activeSessionIdRef.current === sessionId && isAtScrollBottom(term);
    term.write(data, () => {
      if (shouldFollowOutput) {
        scrollToBottomIfActive(sessionId, term);
      }
    });
  }

  function ensureTerminal(sessionId: string, container: HTMLDivElement) {
    const existing = terminalRef.current.get(sessionId);
    if (existing) {
      if (containerRef.current.get(sessionId) === container) {
        return;
      }
      // Remount path: rebuild xterm against the new DOM container.
      try {
        existing.term.dispose();
      } catch {
      }
      terminalRef.current.delete(sessionId);
      lastResizeRef.current.delete(sessionId);
      logBridge.write({
        level: "info",
        scope: "terminal",
        message: "Recreating xterm instance for remount",
        meta: { sessionId }
      });
    }
    logBridge.write({
      level: "info",
      scope: "terminal",
      message: "Creating xterm instance",
      meta: { sessionId }
    });

    const term = new Terminal({
      convertEol: true,
      cursorBlink: true,
      scrollback: 10000,
      fontSize: 11,
      lineHeight: 1.18,
      letterSpacing: 0,
      fontFamily: "Menlo, Monaco, Consolas, \"Liberation Mono\", monospace",
      theme: {
        background: "#0b0d10",
        foreground: "#d9e1ee",
        cursor: "#e8eefc",
        selectionBackground: "rgba(120, 145, 190, 0.35)",
        black: "#0b0d10",
        red: "#ff6b6b",
        green: "#39d98a",
        yellow: "#f5c86a",
        blue: "#6aa9ff",
        magenta: "#c792ea",
        cyan: "#66d9ef",
        white: "#d9e1ee",
        brightBlack: "#5e6a7f",
        brightRed: "#ff8a8a",
        brightGreen: "#5ae7a1",
        brightYellow: "#ffd98a",
        brightBlue: "#8cc0ff",
        brightMagenta: "#ddb0ff",
        brightCyan: "#8ae8ff",
        brightWhite: "#f3f6fc"
      }
    });

    const fitAddon = new FitAddon();
    const linkAddon = new WebLinksAddon();
    term.loadAddon(fitAddon);
    term.loadAddon(linkAddon);
    installCodexScrollbackGuard(sessionId, term);
    term.open(container);
    fitAddon.fit();

    // xterm.js 5.x 中 attachCustomKeyEventHandler 需通过方法调用注册
    term.attachCustomKeyEventHandler((event: KeyboardEvent) => {
      const key = event.key.toLowerCase();
      const isMod = event.ctrlKey || event.metaKey;

      logBridge.write({
        level: "info",
        scope: "terminal",
        message: "[key] attachCustomKeyEventHandler",
        meta: { sessionId, key: event.key, ctrlKey: event.ctrlKey, metaKey: event.metaKey, shiftKey: event.shiftKey, hasSelection: term.hasSelection() }
      });

      // Ctrl/Cmd + C — 有选区时复制到剪贴板，无选区时发送中断
      if (key === "c" && isMod) {
        if (term.hasSelection()) {
          const selection = term.getSelection();
          logBridge.write({ level: "info", scope: "terminal", message: "[key] copying selection", meta: { sessionId, selectionLength: selection.length } });
          void navigator.clipboard.writeText(selection)
            .then(() => logBridge.write({ level: "info", scope: "terminal", message: "[key] copy success", meta: { sessionId } }))
            .catch((err) => logBridge.write({ level: "warn", scope: "terminal", message: "[key] copy failed", meta: { sessionId, error: err instanceof Error ? err.message : String(err) } }));
          term.clearSelection();
          return false;
        }
        logBridge.write({ level: "info", scope: "terminal", message: "[key] no selection, sending interrupt", meta: { sessionId } });
        return true;
      }

      // Ctrl/Cmd + V — 先尝试读取图片，fallback 到文本粘贴
      if (key === "v" && isMod) {
        logBridge.write({ level: "info", scope: "terminal", message: "[key] pasting", meta: { sessionId } });
        event.preventDefault();

        const session = useSessionStore.getState().sessions.find((s) => s.sessionId === sessionId);
        if (!session || !session.cwd) {
          logBridge.write({ level: "info", scope: "terminal", message: "[key] paste skipped: no session/cwd", meta: { sessionId } });
          return false;
        }

        const isWindows = /Win32|Win64/.test(navigator.platform);
        const supportsImagePaste = session.provider === "codex" || session.provider === "gemini" || isWindows;

        if (supportsImagePaste) {
          // 先尝试 IPC 读取剪贴板图片（主进程有完整权限）
          logBridge.write({ level: "info", scope: "terminal", message: "[key] trying image paste via IPC", meta: { sessionId } });
          void fileBridge.saveAttachmentImage({ cwd: session.cwd, sessionId })
            .then((result) => {
              if (result?.ok && result.relPath) {
                logBridge.write({ level: "info", scope: "terminal", message: "[key] image pasted", meta: { sessionId, relPath: result.relPath } });
                ptyBridge.input(sessionId, `@${result.relPath}`);
                return;
              }
              logBridge.write({ level: "info", scope: "terminal", message: "[key] no image in clipboard, falling back to text", meta: { sessionId, reason: result?.reason } });
              // fallback 到文本粘贴
              navigator.clipboard.readText()
                .then((text) => {
                  if (text) ptyBridge.input(sessionId, text);
                })
                .catch(() => {});
            })
            .catch((err) => {
              logBridge.write({ level: "warn", scope: "terminal", message: "[key] image paste failed", meta: { sessionId, error: err instanceof Error ? err.message : String(err) } });
              navigator.clipboard.readText()
                .then((text) => { if (text) ptyBridge.input(sessionId, text); })
                .catch(() => {});
            });
        } else {
          // 不支持图片粘贴的 provider，直接文本粘贴
          navigator.clipboard.readText()
            .then((text) => {
              logBridge.write({ level: "info", scope: "terminal", message: "[key] text pasted", meta: { sessionId, textLength: text?.length ?? 0 } });
              if (text) ptyBridge.input(sessionId, text);
            })
            .catch((err) => logBridge.write({ level: "warn", scope: "terminal", message: "[key] text paste failed", meta: { sessionId, error: err instanceof Error ? err.message : String(err) } }));
        }
        return false;
      }

      return true;
    });

    const refreshTerminal = () => {
      window.requestAnimationFrame(() => {
        try {
          if (isAtScrollBottom(term)) {
            scrollToBottomIfActive(sessionId, term);
          }
          term.refresh(0, Math.max(0, term.rows - 1));
        } catch {
        }
      });
    };

    const onPaste = (event: ClipboardEvent) => {
      logBridge.write({
        level: "info",
        scope: "terminal",
        message: "[paste] event fired",
        meta: { sessionId, target: (event.target as HTMLElement)?.tagName, activeSessionId: activeSessionIdRef.current }
      });

      if (activeSessionIdRef.current !== sessionId) {
        logBridge.write({ level: "info", scope: "terminal", message: "[paste] skipped: not active session", meta: { sessionId, activeSessionId: activeSessionIdRef.current } });
        return;
      }
      const session = useSessionStore.getState().sessions.find((item) => item.sessionId === sessionId);
      if (!session) {
        logBridge.write({ level: "warn", scope: "terminal", message: "[paste] skipped: session not found", meta: { sessionId } });
        return;
      }
      const isWindows = /Win32|Win64/.test(navigator.platform);
      const supportsImagePaste = session.provider === "codex" || session.provider === "gemini" || isWindows;
      if (!supportsImagePaste) {
        logBridge.write({ level: "info", scope: "terminal", message: "[paste] skipped: provider does not support image paste", meta: { sessionId, provider: session.provider } });
        return;
      }
      if (!session.cwd) {
        logBridge.write({ level: "warn", scope: "terminal", message: "[paste] skipped: no cwd", meta: { sessionId } });
        return;
      }

      const items = Array.from(event.clipboardData?.items || []);
      const types = items.map((i) => i.type);
      logBridge.write({ level: "info", scope: "terminal", message: "[paste] clipboard items", meta: { sessionId, types } });

      const imageItem = items.find((item) => String(item.type || "").toLowerCase().startsWith("image/"));
      if (!imageItem) {
        logBridge.write({ level: "info", scope: "terminal", message: "[paste] no image item found", meta: { sessionId, types } });
        return;
      }

      event.preventDefault();
      event.stopPropagation();
      logBridge.write({ level: "info", scope: "terminal", message: "[paste] image item found, processing", meta: { sessionId, mimeType: imageItem.type } });

      if (pasteInFlightRef.current.has(sessionId)) {
        logBridge.write({ level: "info", scope: "terminal", message: "[paste] skipped: already in flight", meta: { sessionId } });
        return;
      }
      pasteInFlightRef.current.add(sessionId);

      const file = imageItem.getAsFile();
      if (!file) {
        logBridge.write({ level: "warn", scope: "terminal", message: "[paste] getAsFile returned null", meta: { sessionId } });
        pasteInFlightRef.current.delete(sessionId);
        return;
      }

      logBridge.write({ level: "info", scope: "terminal", message: "[paste] reading file", meta: { sessionId, size: file.size, name: file.name } });

      const reader = new FileReader();
      reader.onload = () => {
        const arrayBuffer = reader.result as ArrayBuffer;
        if (!arrayBuffer || arrayBuffer.byteLength === 0) {
          logBridge.write({ level: "warn", scope: "terminal", message: "[paste] empty array buffer", meta: { sessionId } });
          pasteInFlightRef.current.delete(sessionId);
          return;
        }
        const bytes = new Uint8Array(arrayBuffer);
        let binary = "";
        const chunk = 8192;
        for (let i = 0; i < bytes.length; i += chunk) {
          binary += String.fromCharCode(...bytes.subarray(i, i + chunk));
        }
        const base64 = btoa(binary);
        logBridge.write({ level: "info", scope: "terminal", message: "[paste] base64 ready", meta: { sessionId, byteLength: arrayBuffer.byteLength, base64Length: base64.length } });

        void fileBridge.saveAttachmentImageBuffer({
          cwd: session.cwd,
          sessionId,
          base64,
          mimeType: imageItem.type || "image/png"
        }).then((result) => {
          if (!result?.ok || !result.relPath) {
            logBridge.write({
              level: "warn",
              scope: "terminal",
              message: "[paste] save failed or skipped",
              meta: { sessionId, reason: result?.reason || "unknown" }
            });
            return;
          }
          logBridge.write({ level: "info", scope: "terminal", message: "[paste] image saved", meta: { sessionId, relPath: result.relPath } });
          ptyBridge.input(sessionId, `@${result.relPath}`);
        }).catch((error) => {
          logBridge.write({
            level: "warn",
            scope: "terminal",
            message: "[paste] saveAttachmentImageBuffer threw",
            meta: { sessionId, error: error instanceof Error ? error.message : String(error) }
          });
        }).finally(() => {
          pasteInFlightRef.current.delete(sessionId);
          try { term.focus(); } catch { }
        });
      };
      reader.onerror = () => {
        logBridge.write({
          level: "warn",
          scope: "terminal",
          message: "[paste] FileReader error",
          meta: { sessionId, error: reader.error?.message || "unknown" }
        });
        pasteInFlightRef.current.delete(sessionId);
      };
      reader.readAsArrayBuffer(file);
    };

    const pasteTarget = term.textarea || container;
    logBridge.write({ level: "info", scope: "terminal", message: "[paste] binding listener", meta: { sessionId, target: (pasteTarget as HTMLElement)?.tagName } });
    const pasteListener = (event: Event) => onPaste(event as ClipboardEvent);
    pasteTarget.addEventListener("paste", pasteListener, true);
    const prevCleanup = pasteCleanupRef.current.get(sessionId);
    if (prevCleanup) prevCleanup();
    pasteCleanupRef.current.set(sessionId, () => {
      logBridge.write({ level: "info", scope: "terminal", message: "[paste] unbinding listener", meta: { sessionId } });
      pasteTarget.removeEventListener("paste", pasteListener, true);
    });

    const writeReplay = (data: string, reset = false) => {
      replayMutedRef.current.add(sessionId);
      const finishReplay = () => {
        scrollToBottomIfActive(sessionId, term);
        refreshTerminal();
        window.requestAnimationFrame(() => {
          replayMutedRef.current.delete(sessionId);
        });
      };
      if (reset) {
        term.reset();
      }
      term.write(data, finishReplay);
    };

    const snapshot = stripEchoedTerminalReports(bufferRef.current.get(sessionId) || "");
    if (snapshot) {
      try {
        writeReplay(snapshot);
      } catch (error) {
        replayMutedRef.current.delete(sessionId);
        logBridge.write({
          level: "warn",
          scope: "terminal",
          message: "Initial snapshot write failed",
          meta: { sessionId, error: error instanceof Error ? error.message : String(error) }
        });
      }
    }

    ptyBridge.snapshot(sessionId).then((serverSnapshot) => {
      const data = stripEchoedTerminalReports(serverSnapshot?.data || "");
      if (!data) return;
      const localSnapshot = bufferRef.current.get(sessionId) || "";
      if (localSnapshot.length >= data.length) return;
      bufferRef.current.set(sessionId, data);
      try {
        writeReplay(data, Boolean(localSnapshot));
      } catch (error) {
        replayMutedRef.current.delete(sessionId);
        logBridge.write({
          level: "warn",
          scope: "terminal",
          message: "Server snapshot write failed",
          meta: { sessionId, error: error instanceof Error ? error.message : String(error) }
        });
      }
    }).catch((error) => {
      logBridge.write({
        level: "warn",
        scope: "terminal",
        message: "Failed to load PTY snapshot",
        meta: { sessionId, error: error instanceof Error ? error.message : String(error) }
      });
    });

    term.onData((data) => {
      if (activeSessionIdRef.current !== sessionId) return;
      if (replayMutedRef.current.has(sessionId)) return;
      const sanitized = stripTerminalReports(data);
      if (!sanitized) return;
      ptyBridge.input(sessionId, sanitized);
    });

    safeResizePty(sessionId, { term, fitAddon });

    terminalRef.current.set(sessionId, { term, fitAddon });
  }

  function setPaneRef(sessionId: string, el: HTMLDivElement | null) {
    if (!el) {
      if (!containerRef.current.has(sessionId)) return;
      logBridge.write({
        level: "info",
        scope: "terminal",
        message: "Pane unmounted",
        meta: { sessionId }
      });
      const existingObserver = resizeObserverRef.current.get(sessionId);
      if (existingObserver) {
        existingObserver.disconnect();
        resizeObserverRef.current.delete(sessionId);
      }
      const pasteCleanup = pasteCleanupRef.current.get(sessionId);
      if (pasteCleanup) {
        pasteCleanup();
        pasteCleanupRef.current.delete(sessionId);
      }
      const raf = fitRafRef.current.get(sessionId);
      if (typeof raf === "number") {
        window.cancelAnimationFrame(raf);
        fitRafRef.current.delete(sessionId);
      }
      const existingTerminal = terminalRef.current.get(sessionId);
      if (existingTerminal) {
        try {
          existingTerminal.term.dispose();
        } catch {
        }
        terminalRef.current.delete(sessionId);
        lastResizeRef.current.delete(sessionId);
        replayMutedRef.current.delete(sessionId);
      }
      containerRef.current.delete(sessionId);
      return;
    }
    if (containerRef.current.get(sessionId) === el && terminalRef.current.has(sessionId)) {
      return;
    }
    logBridge.write({
      level: "info",
      scope: "terminal",
      message: "Pane mounted",
      meta: { sessionId }
    });
    containerRef.current.set(sessionId, el);
    ensureTerminal(sessionId, el);

    const scheduleFit = () => {
      const prev = fitRafRef.current.get(sessionId);
      if (typeof prev === "number") window.cancelAnimationFrame(prev);
      const raf = window.requestAnimationFrame(() => {
        const entry = terminalRef.current.get(sessionId);
        if (!entry) return;
        entry.fitAddon.fit();
        safeResizePty(sessionId, entry);
      });
      fitRafRef.current.set(sessionId, raf);
    };

    scheduleFit();

    if (typeof ResizeObserver !== "undefined") {
      const existingObserver = resizeObserverRef.current.get(sessionId);
      if (existingObserver) existingObserver.disconnect();
      const observer = new ResizeObserver(() => scheduleFit());
      observer.observe(el);
      resizeObserverRef.current.set(sessionId, observer);
    }
  }

  function fitActiveTerminal() {
    const sid = activeSessionIdRef.current;
    if (!sid) return;
    const entry = terminalRef.current.get(sid);
    if (!entry) return;
    const shouldFollowOutput = isAtScrollBottom(entry.term);
    entry.fitAddon.fit();
    safeResizePty(sid, entry);
    if (shouldFollowOutput) {
      scrollToBottomIfActive(sid, entry.term);
    }
    entry.term.focus();
  }

  useEffect(() => {
    const offData = ptyBridge.onData(({ sessionId, data }) => {
      appendBuffer(sessionId, data);
      ingestOutput(sessionId, data);
      const entry = terminalRef.current.get(sessionId);
      if (entry && containerRef.current.has(sessionId)) {
        try {
          writeLiveTerminalData(sessionId, entry.term, data);
        } catch (error) {
          logBridge.write({
            level: "warn",
            scope: "terminal",
            message: "term.write failed",
            meta: { sessionId, error: error instanceof Error ? error.message : String(error) }
          });
        }
      }
    });

    const offExit = ptyBridge.onExit(({ sessionId, exitCode }) => {
      const line = `\r\n[process exited with code ${exitCode}]\r\n`;
      appendBuffer(sessionId, line);
      const entry = terminalRef.current.get(sessionId);
      if (entry && containerRef.current.has(sessionId)) {
        try {
          writeLiveTerminalData(sessionId, entry.term, line);
        } catch (error) {
          logBridge.write({
            level: "warn",
            scope: "terminal",
            message: "term.write exit line failed",
            meta: { sessionId, error: error instanceof Error ? error.message : String(error) }
          });
        }
      }
      markExited(sessionId, exitCode);
      logBridge.write({
        level: "info",
        scope: "terminal",
        message: "PTY exited",
        meta: { sessionId, exitCode }
      });
    });

    const idleTimer = window.setInterval(() => {
      refreshRuntimeStatuses();
    }, 1000);

    return () => {
      offData();
      offExit();
      window.clearInterval(idleTimer);
      for (const observer of resizeObserverRef.current.values()) {
        observer.disconnect();
      }
      for (const cleanup of pasteCleanupRef.current.values()) {
        cleanup();
      }
      for (const raf of fitRafRef.current.values()) {
        window.cancelAnimationFrame(raf);
      }
      resizeObserverRef.current.clear();
      pasteCleanupRef.current.clear();
      fitRafRef.current.clear();
      for (const { term } of terminalRef.current.values()) {
        term.dispose();
      }
      terminalRef.current.clear();
      containerRef.current.clear();
      replayMutedRef.current.clear();
    };
  }, [ingestOutput, markExited, refreshRuntimeStatuses]);

  useEffect(() => {
    fitActiveTerminal();
    const raf = window.requestAnimationFrame(() => fitActiveTerminal());
    logBridge.write({
      level: "info",
      scope: "terminal",
      message: "Active session changed",
      meta: { activeSessionId }
    });
    const onResize = () => fitActiveTerminal();
    window.addEventListener("resize", onResize);
    return () => {
      window.cancelAnimationFrame(raf);
      window.removeEventListener("resize", onResize);
    };
  }, [activeSessionId]);

  useEffect(() => {
    window.__ZEELIN_TEST__ = {
      getActiveSessionId: () => activeSessionIdRef.current || "",
      getSessionBuffer: (sessionId: string) => bufferRef.current.get(sessionId) || "",
      getPaneDisplay: (sessionId: string) => {
        const el = containerRef.current.get(sessionId);
        if (!el) return null;
        return window.getComputedStyle(el).display;
      },
      getLastResize: (sessionId: string) => lastResizeRef.current.get(sessionId) || null,
      getTerminalScrollState: (sessionId: string) => {
        const entry = terminalRef.current.get(sessionId);
        if (!entry) return null;
        const buffer = entry.term.buffer.active;
        const viewport = containerRef.current.get(sessionId)?.querySelector(".xterm-viewport") as HTMLElement | null;
        return {
          baseY: buffer.baseY,
          viewportY: buffer.viewportY,
          rows: entry.term.rows,
          scrollTop: viewport?.scrollTop ?? 0,
          scrollHeight: viewport?.scrollHeight ?? 0,
          clientHeight: viewport?.clientHeight ?? 0
        };
      },
      scrollTerminalLines: (sessionId: string, lines: number) => {
        const entry = terminalRef.current.get(sessionId);
        if (!entry) return false;
        entry.term.scrollLines(lines);
        return true;
      },
      appendTerminalData: (sessionId: string, data: string) => {
        const entry = terminalRef.current.get(sessionId);
        if (!entry) return false;
        writeLiveTerminalData(sessionId, entry.term, data);
        return true;
      },
      destroyAllSessions: () => {
        useSessionStore.getState().destroyAll();
        return true;
      },
      simulateImagePaste: async (sessionId: string, base64: string, mimeType = "image/png") => {
        const session = useSessionStore.getState().sessions.find((s) => s.sessionId === sessionId);
        if (!session || !session.cwd) {
          return { ok: false, reason: "no-session-or-cwd" };
        }
        try {
          const result = await fileBridge.saveAttachmentImageBuffer({
            cwd: session.cwd,
            sessionId,
            base64,
            mimeType
          });
          if (result?.ok && result.relPath) {
            ptyBridge.input(sessionId, `@${result.relPath}`);
            return { ok: true, relPath: result.relPath, absPath: result.absPath };
          }
          return { ok: false, reason: result?.reason || "save-failed" };
        } catch (error) {
          return { ok: false, reason: error instanceof Error ? error.message : String(error) };
        }
      }
    };

    return () => {
      // @ts-expect-error test hook
      delete window.__ZEELIN_TEST__;
    };
  }, []);

  return {
    setPaneRef,
    fitActiveTerminal
  };
}
