export const TERMINAL_BUFFER_LIMIT = 300000;

export function appendLimitedBuffer(prev: string, chunk: string, limit = TERMINAL_BUFFER_LIMIT) {
  const merged = prev + chunk;
  return merged.length > limit ? merged.slice(-limit) : merged;
}

export function stripTerminalReports(data: string) {
  return (
    data
      // Cursor position / device attribute / status reports generated by xterm.
      .replace(/\x1b\[\??[0-9;]*[Rcn]/g, '')
      // OSC color query replies, for example ESC ] 10;rgb:cccc/cccc/cccc BEL.
      .replace(/\x1b\](?:10|11|12|4;[0-9]+);rgb:[0-9a-fA-F/]+\x07/g, '')
      .replace(/\x1b\](?:10|11|12|4;[0-9]+);rgb:[0-9a-fA-F/]+\x1b\\/g, '')
  );
}

export function stripEchoedTerminalReports(data: string) {
  return data
    .split(/\r?\n/)
    .filter((line) => {
      const trimmed = line.trim();
      if (/^(?:;)?(?:\d+R|\d+c\d+)(?:;|$)/.test(trimmed)) return false;
      if (
        /^zsh: (?:command not found|no such file or directory): (?:\d+R|\d+c\d+|rgb:)/.test(trimmed)
      )
        return false;
      return true;
    })
    .join('\r\n');
}

